# Generated by Django 5.0.4 on 2024-05-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutualist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom et Prénom')),
                ('phone', models.CharField(max_length=10, verbose_name='Numéro de téléĥone')),
            ],
            options={
                'verbose_name': 'Mutualiste',
                'verbose_name_plural': 'Mutualistes',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='contenu')),
            ],
            options={
                'verbose_name': 'Sms',
                'verbose_name_plural': 'Sms',
            },
        ),
    ]
